### PR TITLE
Docks scrollbar

### PR DESCRIPTION
**Pull request by coozoo**
Attempt to fix this bug with placing all docks into dock with scrollbar
[Laptop 1366x768 UI jumping](https://github.com/OpenHantek/openhantek/issues/223)

### CODE REVIEW

**Comment by davidgraeff** [comment]
Thanks :) but I have another comment here as well. What actually makes sense is to just replace the base qwidget of each dock with a scroll area. Putting everything into another dock will be super confusing if you actually move the docks within the window. I don't know if you understood the concept of docks. You can freely move them around within the main window. One solution to your height problem is for example to close one of the docks or move it to the other side of the window.

**Comment by coozoo** [comment]
> One solution to your height problem is for example to close one of the docks or move it to the other side of the window.

Yes but, it's almost impossible to do because it's jumping like a hell ) and you can grab the dock only by estimating where the header of dock will be after jump )

**Comment by osmanypereira** [comment]
Hi All -
My apologies if I'm posting this in the wrong place. I have been waiting for a full functioning build (binaries) for windows, including the driver. From the discussions I got the impression that now there is a version that works under windows.
Can someone point me to the place where I can download windows' binaries?
Thanks in advance.

**Comment by coozoo** [comment]
@osmanypereira if you able to wait few hours I can post a build (succeeded to croscompile it yesterday eve :))

**Comment by osmanypereira** [comment]
coozoo, thank you very much, it is greatly appreciated.

**Comment by coozoo** [comment]
@osmanypereira  here
keep in mind that if your device differ from 6022be you need to change vid/pid in driver inf file
[openhantek.7z](https://github.com/coozoo/openhantek/releases/download/Fixes/openhantek.7z)

**Comment by osmanypereira** [comment]
Thank you very much. I'll try out in the next two hours and let you know how it went.

**Comment by coozoo** [comment]
@osmanypereira ur welcome.  oh and sorry I forgot to put platforms folder, so if you already downloaded it simply just redownload. :)

**Comment by osmanypereira** [comment]
coozo - thank you. It worked for me. Since I do not have Qt installed I just had to set an environment variable to point to the platforms folder. I had a different weird problem with the driver. After letting my windows go to sleep in the laptop, on the next day the driver wouldn't load with the message "Upload in progress". I checked the driver installation and realized that my Hantek 6022B is reporting a different Vendor ID, so I corrected the device_inf file and reinstalled the driver, which fixed the problem. The vendor ID changed from "VID_04B5" to "VID_04B4". I'll monitor to see if the Vendor ID changes again; weird!

**Pull request closed without merging**
