### PR TITLE
Windows Fix

### PR DESCRIPTION
**Pull request by circuit-specialists**
Fixed lib.exe error
Fixed compile error
Preconfigured settings for VS Code

### CODE REVIEW

**Comment by circuit-specialists** [comment]
I've done some more testing. The reason lib.exe fails is based on the generator cmake is using on windows. As long as the generator is using "Visual Studio 15 2017 Win64", then it configures and generates correctly. So leaving out this change the fftw_on_windows.cmake, and leaving it with the the auto directory, may be a good a thing. If the configure fails, it's an easy way to know you're using the wrong generator. Instead, in the windows documentation section it should just like what generator cmake needs to make. The .vscode directory helps with that exactly by specifying the generator for cmake to use.

**Comment by circuit-specialists** [comment]
I've made the changes to the fftw3.h directory to place it into the true openhantek/src.

**Comment by LameLefty** [comment]
I managed to build a working Win10-64 bit version today using these fixes. However, my MS Visual Studio installation location and version numbers are both different than those specified in the changed code. Manually editing several of the appropriate files fixed those issues. In addition, for some reason even after parsing the main CMakeLists.txt file to create a Visual Studio project "solution" file did not allow Visual Studio to build the project properly until I again manually edited the base CMakeLists.txt file to specify the location of the Qt5 libraries. Finally, after all of that, I was able to build a working binary and run it successfully with my Hantek 6022BE.

**Comment by davidgraeff** [comment]
I'm sorry guys, I can't accept a pull request that binds this project to one specific visual studio version. That will be soon outdated.
If you find a more general approach I would be happy to accept it.

**Pull request closed without merging**
