### PR TITLE
Fix spectrum display

### PR DESCRIPTION
**Pull request by BrunoMaire**
The loop was controlled with a different variable than the previous loops.

### CODE REVIEW

**Comment by BrunoMaire** [comment]
Fix UI segfaults #32
2090: By expanding enum ControlIndex in hantek/control.h, empty pending controls were created.

**Comment by BrunoMaire** [comment]
Hi,
This is my first contribution to GitHub.
I wanted to make one pull request for each fix as they are not related. But somehow they ended in the same pull request.
Best regards,
Bruno

**Comment by BrunoMaire** [comment]
Ups

**Comment by igor-stoppa** [comment]
@BrunoMaire With Github, if you want to have fully independent pull requests, you have to create a separate branch for each pull request.
Thanks for the patches, I'll try to find time to test them.

**Comment by igor-stoppa** [comment]
@BrunoMaire after upgrading to FC 24 I do not experience any more problems with the stock repo.
Both on FC 24 and Ubuntu 16.04

**Comment by BrunoMaire** [comment]
@igor-stoppa sorry I can't follow you.
Is "stock repo" with or without my modifications?
Please tell me what FC 24 is.

**Comment by igor-stoppa** [comment]
@BrunoMaire  with "stock repo" I meant the HEAD of the master branch. Without your patches.
FC 24 is Fedora Core 24, as I wrote in the bug I originally filed, I was initially using Fedora Core 23.
Lately I upgraded to 24.  So I wanted to first reproduce the issue, before testing your patches.
When I tried it, I didn't have the scope available, so I just started the UI. But even this was failing, previously. I built it also on an Ubuntu 16.04 and it worked equally well, without crashes and without patching.

**Comment by BrunoMaire** [comment]
@igor-stoppa thank for the explanation. Maybe I should be more verbose on the bugs I fixed:
UI segfaults #32 After rereading the issue I have to admit that it could be a complete other issue with a similar behavement. The issue I fixed in hantek/control.h happens if you read out a DSO2090. It will not happen with a DSO6022BE. I think that it will also crash reading out DSO2250 or DSO5200 because the modification was made for DSO6022BE. It is even possible, that I introduce a bug for DSO2250 and DSO5200 as I supposed that they will be affected the same way as the DSO2090. I only have a DSO2090 to do tests.
Spectrum Display just shows a straight line on the level of the first point. This is due to the fact that the iterator in the for-loop is not used to read out the values of the array.

**Comment by davidgraeff** [comment]
If there's no objection, I'll merge the commits

**Pull request merged**
